### ISSUE TITLE
Installation Ubuntu

### ISSUE THREAD

**Issue by PRijnbeek** [EHDEN/NetworkDashboards#4]
at this step:
docker-compose run --rm superset ./docker-init.sh

I get this error:

psycopg2.ProgrammingError: relation "clusters" already exists

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/superset/superset/bin/superset", line 31, in <module>
    cli()
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask/cli.py", line 426, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask_migrate/cli.py", line 134, in upgrade
    _upgrade(directory, revision, sql, tag, x_arg)
  File "/usr/local/lib/python3.6/site-packages/flask_migrate/__init__.py", line 95, in wrapped
    f(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask_migrate/__init__.py", line 280, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/usr/local/lib/python3.6/site-packages/alembic/command.py", line 276, in upgrade
    script.run_env()
  File "/usr/local/lib/python3.6/site-packages/alembic/script/base.py", line 475, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/usr/local/lib/python3.6/site-packages/alembic/util/pyfiles.py", line 90, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/lib/python3.6/site-packages/alembic/util/compat.py", line 177, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/superset/superset/migrations/env.py", line 114, in <module>
    run_migrations_online()
  File "/home/superset/superset/migrations/env.py", line 106, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/usr/local/lib/python3.6/site-packages/alembic/runtime/environment.py", line 839, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/usr/local/lib/python3.6/site-packages/alembic/runtime/migration.py", line 362, in run_migrations
    step.migration_fn(**kw)
  File "/home/superset/superset/migrations/versions/4e6a06bad7a8_init.py", line 55, in upgrade
    sa.UniqueConstraint("cluster_name"),
  File "<string>", line 8, in create_table
  File "<string>", line 3, in create_table
  File "/usr/local/lib/python3.6/site-packages/alembic/operations/ops.py", line 1248, in create_table
    return operations.invoke(op)
  File "/usr/local/lib/python3.6/site-packages/alembic/operations/base.py", line 345, in invoke
    return fn(self, operation)
  File "/usr/local/lib/python3.6/site-packages/alembic/operations/toimpl.py", line 101, in create_table
    operations.impl.create_table(table)
  File "/usr/local/lib/python3.6/site-packages/alembic/ddl/impl.py", line 252, in create_table
    self._exec(schema.CreateTable(table))
  File "/usr/local/lib/python3.6/site-packages/alembic/ddl/impl.py", line 134, in _exec
    return conn.execute(construct, *multiparams, **params)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/sql/ddl.py", line 72, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1050, in _execute_ddl
    compiled,
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) relation "clusters" already exists

[SQL: 
CREATE TABLE clusters (
	created_on TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	changed_on TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	id SERIAL NOT NULL, 
	cluster_name VARCHAR(250), 
	coordinator_host VARCHAR(255), 
	coordinator_port INTEGER, 
	coordinator_endpoint VARCHAR(255), 
	broker_host VARCHAR(255), 
	broker_port INTEGER, 
	broker_endpoint VARCHAR(255), 
	metadata_last_refreshed TIMESTAMP WITHOUT TIME ZONE, 
	created_by_fk INTEGER, 
	changed_by_fk INTEGER, 
	PRIMARY KEY (id), 
	UNIQUE (cluster_name), 
	FOREIGN KEY(created_by_fk) REFERENCES ab_user (id), 
	FOREIGN KEY(changed_by_fk) REFERENCES ab_user (id)
)

]
(Background on this error at: http://sqlalche.me/e/f405)

**Comment by PRijnbeek** [comment]
you should skip in the ReadMe:
docker-compose run --rm -e FLASK_APP=superset superset flask fab create-db

since that already creates the db.

**Comment by joaorafaelalmeida** [comment]
The command `docker-compose run --rm -e FLASK_APP=superset superset flask fab create-db` was necessary for some Ubuntu versions. However, in other Unix distributions, this command raised that issue. 
Do you still have the issue with the command `docker-compose run --rm superset ./docker-init.sh`? Since you already had the superset working, I think you can skip the installation steps and go directly to the demo setup.

**Comment by PRijnbeek** [comment]
Superset is working now

I now have an issue with getting the Django app running. It needs to be set in development mode otherwise the ALLOWED_HOSTS has to be set. figuring this out now..

Already found the  DASHBOARD_VIEWER_ENV="development" that needs to be set but that did not help. I now fix it to DEBUG = TRUE and rebuild to see if this works

**Comment by PRijnbeek** [comment]
i see this:
dashboard_viewer_1  | CommandError: You must set settings.ALLOWED_HOSTS if DEBUG is False.
dashboard_viewer_dashboard_viewer_1 exited with code 1

I now changed settings.py in the django app to:
DEBUG = get_env_variable("DASHBOARD_VIEWER_ENV") == "development"
DEBUG = TRUE
ALLOWED_HOSTS = ['localhost', '127.0.0.1']

but when i run it it looks it did not see the code was changed. Do I need to rebuild it in some way? (not sure how this works under Docker)

**Comment by joaorafaelalmeida** [comment]
Could you please show me the output for the following commands:
- `docker ps -a | grep dashboard`
- `docker logs dashboard_viewer_dashboard_viewer_1`

**Comment by PRijnbeek** [comment]
b31a250e6261        dashboard_viewer_dashboard_viewer   "/bin/sh -c ./docker…"   36 minutes ago      Exited (1) 36 minutes ago                                gracious_jepsen
45e765e0fd4e        dashboard_viewer_dashboard_viewer   "python app.py"          37 minutes ago      Exited (2) 37 minutes ago                                admiring_nash
17e142e99026        dashboard_viewer_superset           "/entrypoint.sh"         About an hour ago   Up About a minute (healthy)     0.0.0.0:8088->8088/tcp   dashboard_viewer_superset_1
21375aa12703        dashboard_viewer_dashboard_viewer   "/bin/sh -c ./docker…"   About an hour ago   Exited (1) About a minute ago                            dashboard_viewer_dashboard_viewer_1
76a34de26099        postgres:10                         "docker-entrypoint.s…"   2 hours ago         Up About a minute               0.0.0.0:5432->5432/tcp   dashboard_viewer_postgres_1
06f072e82e7e        redis:3.2                           "docker-entrypoint.s…"   2 hours ago         Up About a minute               0.0.0.0:6379->6379/tcp   dashboard_viewer_redis_1


and

+ python manage.py runserver 0.0.0.0:8000
CommandError: You must set settings.ALLOWED_HOSTS if DEBUG is False.
+ python manage.py runserver 0.0.0.0:8000
CommandError: You must set settings.ALLOWED_HOSTS if DEBUG is False.
+ python manage.py runserver 0.0.0.0:8000
CommandError: You must set settings.ALLOWED_HOSTS if DEBUG is False.
+ python manage.py runserver 0.0.0.0:8000
CommandError: You must set settings.ALLOWED_HOSTS if DEBUG is False.
+ python manage.py runserver 0.0.0.0:8000
CommandError: You must set settings.ALLOWED_HOSTS if DEBUG is False.
+ python manage.py runserver 0.0.0.0:8000
CommandError: You must set settings.ALLOWED_HOSTS if DEBUG is False.
+ python manage.py runserver 0.0.0.0:8000
CommandError: You must set settings.ALLOWED_HOSTS if DEBUG is False.
+ python manage.py runserver 0.0.0.0:8000
CommandError: You must set settings.ALLOWED_HOSTS if DEBUG is False.
+ python manage.py runserver 0.0.0.0:8000
CommandError: You must set settings.ALLOWED_HOSTS if DEBUG is False.
+ python manage.py runserver 0.0.0.0:8000
CommandError: You must set settings.ALLOWED_HOSTS if DEBUG is False.
+ python manage.py runserver 0.0.0.0:8000
CommandError: You must set settings.ALLOWED_HOSTS if DEBUG is False.
+ python manage.py runserver 0.0.0.0:8000
CommandError: You must set settings.ALLOWED_HOSTS if DEBUG is False.

**Comment by PRijnbeek** [comment]
I now ran :

 `docker system prune`

to remove the stopped once.

then did:
`docker rmi dashboard_viewer_dashboard_viewer`

to remove the old image and then created the image again after setting DEBUG = 1:

`docker-compose run --rm dashboard_viewer ./docker-init.sh`

Then the django image works (still need to set the ALLOWED_HOSTS it looks like though

**Comment by joaorafaelalmeida** [comment]
Well, I noticed that in the docker-compose file, there are two variables (DASHBOARD_VIEWER_ENV and SUPERSET_ENV) set as `production`. I need you to change them to `development` and the variable DEBUG to false, please. Then, do the following commands `docker-compose down` (to stop and remove the existant containers) and `docker-compose up -d` (to create new ones). Did it work for you?

**Comment by PRijnbeek** [comment]
ok reset the settings.py and then did what you asked.

CONTAINER ID        IMAGE                               COMMAND                  CREATED             STATUS                             PORTS                    NAMES
2f75909b374e        dashboard_viewer_superset           "/entrypoint.sh"         17 seconds ago      Up 15 seconds (health: starting)   0.0.0.0:8088->8088/tcp   dashboard_viewer_superset_1
ebb01c3205d9        dashboard_viewer_dashboard_viewer   "/bin/sh -c ./docker…"   18 seconds ago      Up 14 seconds                      0.0.0.0:8000->8000/tcp   dashboard_viewer_dashboard_viewer_1
fe39949a63d0        redis:3.2                           "docker-entrypoint.s…"   18 seconds ago      Up 16 seconds                      0.0.0.0:6379->6379/tcp   dashboard_viewer_redis_1
cdc22ca3a6fd        postgres:10                         "docker-entrypoint.s…"   2 minutes ago       Up 2 minutes                       0.0.0.0:5432->5432/tcp   dashboard_viewer_postgres_1

but is see this for /admin

<img width="1158" alt="image" src="https://user-images.githubusercontent.com/7252105/68091177-c968d000-fe7c-11e9-9772-245d68bc319f.png">

**Comment by PRijnbeek** [comment]
If i add the ip it i can enter the DJANGO admin part.

Note: I am running this now on AWS so we can all access it and play with it!

**Comment by joaorafaelalmeida** [comment]
I was answering you that. If you are running it in a remote server, you need to add the IP in the ALLOWED_HOSTS. So, now you can enter the base URL and do see the following message "No visible tabs stored"?

**Comment by PRijnbeek** [comment]
I have finished the installation and now see the dashboard:

<img width="2316" alt="image" src="https://user-images.githubusercontent.com/7252105/68091432-d89d4d00-fe7f-11e9-835b-1843c7f2a0c2.png">

http://34.246.189.234:8000

(IP will change once I selected domain and set it to https)

**Comment by joaorafaelalmeida** [comment]
I notice now that there is an issue related to the dashboard permissions, (we may forget to add a note about this in the readme file).  Let me see what is missing, and I will tell you how to fix it.
To replicate the issue, just open the URL (http://34.246.189.234:8000) in a private tab or log out of superset.

**Comment by joaorafaelalmeida** [comment]
The missing step is this one (I already update the readme file with this information):

5. Update the public permissions to see the dashboards
- In Superset go to "Security" -> "List Roles"
- Select the "Edit record" button from the public role.
- In the Permissions field, add the following categories:
    - can explore JSON on Superset
    - can dashboard on Superset
    - all datasource access on all_datasource_access
    - can csrf token on Superset

**Comment by PRijnbeek** [comment]
works but a few to add still:

![image](https://user-images.githubusercontent.com/7252105/68091681-d38dcd00-fe82-11e9-99cb-7c89603d4942.png)

**Comment by aspedrosa** [comment]
Those are superset errors/issues.
The first one, superset is trying to fetch the favorite status of the dashboard with no user logged in.
The second one is related to permissions. You can add the permission "can list on CssTemplateAsyncModelView" to the public role to solve it.

**Comment by PRijnbeek** [comment]
The second one is indeed solved now.

The first one not yet.

We now are on www.test-dashboard.ehden.eu:8000
